name: tmdb
description: A TheMoviedb.org (TMDB) library for Dart.
version: 0.0.2-alpha.1
author: Josep Sayol <josep.sayol@gmail.com>
homepage: https://github.com/jsayol/dart-tmdb

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  http: '>=0.11.0 <0.12.0'

#dev_dependencies:
#  test: '>=0.12.0 <0.13.0'
